### ISSUE TITLE
Model loading error while running facialDetails.py

### ISSUE THREAD

**Issue by hand-in-green** [apchenstu/Facial_Details_Synthesis#16]
I'm sorry to distrubing you. There is an error when I running facialDetails.py I wonder if it's related to the version of pytorch which I use is 0.4.0 with cuda91. Here is the error

Traceback (most recent call last):
  File "facialDetails.py", line 307, in <module>
    main(args)
  File "facialDetails.py", line 233, in main
    DFDN = {'forehead': create_model(args)}
  File "F:\pycharmProgram\released_v0.1\DFDN\models\models.py", line 10, in create_model
    model.initialize(opt)
  File "F:\pycharmProgram\released_v0.1\DFDN\models\pix2pix_model.py", line 79, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch)
  File "F:\pycharmProgram\released_v0.1\DFDN\models\base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "D:\Anaconda3\envs\py3.6\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UnetGenerator:
        Unexpected key(s) in state_dict: "model.model.1.model.2.num_batches_tracked", "model.model.1.model.3.model.2.num_batches_tracked", "model.model.1.model.3.model.3.model.2.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.2.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.3.model.2.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.3.model.6.num_batches_tracked", "model.model.1.model.3.model.3.model.3.model.6.num_batches_tracked", "model.model.1.model.3.model.3.model.6.num_batches_tracked", "model.model.1.model.3.model.6.num_batches_tracked", "model.model.1.model.6.num_batches_tracked".

Waiting for your answer, thank you

**Comment by apchenstu** [comment]
It looks like inconsistent between checkpoint and models,  I think you may need try to update your pytorch to a newer verison(e.g. >=1.0). Thanks.
