### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by bushiwoxixi** [apchenstu/Facial_Details_Synthesis#39]
Thank you for your work. I run facialDetails.py with the following error:

Traceback (most recent call last):
  File "facialDetails.py", line 307, in <module>
    main(args)
  File "facialDetails.py", line 284, in main
    displacementMap, normalMap = predict_details(save_texture_path, args)
  File "facialDetails.py", line 171, in predict_details
    testset, areas = loadimage(image_root,args)
  File "facialDetails.py", line 134, in loadimage
    hsv = np.array(rgb2hsv(img))
  File "D:\python37\lib\site-packages\skimage\color\colorconv.py", line 249, in
    input_is_one_pixel = rgb.ndim == 1
AttributeError: 'Image' object has no attribute 'ndim'

What is the cause of this error and how can I solve it？Thank you.

**Comment by IQ17** [comment]
try conda install scikit-image=0.14.2

**Comment by bushiwoQAQ** [comment]
> try conda install scikit-image=0.14.2

Thank you ! I tried to change the version of scikit-image and the problem was solved.

**Comment by SlimeVRX** [comment]
> try conda install scikit-image=0.14.2

Thank you!
