### ISSUE TITLE
can not create processed/019615.box'

### ISSUE THREAD

**Issue by xuming0629** [apchenstu/Facial_Details_Synthesis#51]
./landmarkDetector
Load preTrain model done.
Load preTrain model done.
sh: 1: FaceLandmarkImg.exe: not found
===> Landmarks detection done.

===> estimating proxy of /home/work/workspace/work2022/study/3dFace/Facial_Details_Synthesis/src/samples/details/019615.jpg 
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: './landmarkDetector/processed/019615.box' -> '/home/work/workspace/work2022/study/3dFace/Facial_Details_Synthesis/src/results/019615/019615.box'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "facialDetails.py", line 338, in <module>
    main(args)
  File "facialDetails.py", line 280, in main
    move_landmark(args.landmark_exe_path, save_path, base_name[0])
  File "facialDetails.py", line 58, in move_landmark
    name+'.box'), os.path.join(save_path, name+'.box'))
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './landmarkDetector/processed/019615.box'

**Comment by Yuqian-He** [comment]
Did you run it on Windows? I had the same issue when I ran it on MacOS & Linux, which do not support .exe file.
